<script setup>
import { t, locale, languageHeaders, apiError, displayError } from './i18n.js';
import { computed, onMounted, ref } from 'vue';
import Questionnaire from './Questionnaire.vue';
import LanguageSwitcher from './LanguageSwitcher.vue';
import { bugTemplate, fieldTypes, choiceTypes, statuses, statusKeys, stateKeys } from './shared.js';
const logged = ref(false), checking = ref(true), password = ref(''), busy = ref(false), error = ref(''), notice = ref('');
const forms = ref([]), draft = ref(null), original = ref(''), view = ref('forms'), preview = ref(false);
const responseForm = ref(null), responses = ref([]), total = ref(0), page = ref(1), filter = ref(''), selected = ref(null);
const clone = value => JSON.parse(JSON.stringify(value));
const dirty = computed(() => draft.value && JSON.stringify(draft.value) !== original.value);
const count = computed(() => forms.value.reduce((sum, f) => sum + (f.responseCount || 0), 0));
const formUrl = computed(() => draft.value ? `${window.location.origin}/f/${draft.value.slug}` : '');
async function api(url, options = {}) {
  const res = await fetch('/api' + url, { ...options, headers: { 'Content-Type': 'application/json', ...languageHeaders(), ...options.headers } });
  const data = await res.json();
  if (!res.ok) { if (res.status === 401) logged.value = false; throw apiError(data, 'errors.operation'); }
  return data;
}
async function run(action) { busy.value = true; error.value = ''; notice.value = ''; try { await action(); } catch (e) { error.value = e; } finally { busy.value = false; } }
async function loadForms() { forms.value = await api('/admin/forms'); }
onMounted(async () => { try { await api('/admin/session'); logged.value = true; await loadForms(); } catch (e) { if (logged.value) error.value = e; } finally { checking.value = false; } });
window.addEventListener('beforeunload', e => { if (dirty.value) { e.preventDefault(); e.returnValue = ''; } });
function mayLeave() { return !dirty.value || window.confirm(t('admin.unsavedConfirm')); }
function back() { if (!mayLeave()) return; view.value = 'forms'; draft.value = null; error.value = ''; notice.value = ''; run(loadForms); }
async function login() { await run(async () => { await api('/admin/login', { method: 'POST', body: JSON.stringify({ password: password.value }) }); logged.value = true; password.value = ''; await loadForms(); }); }
async function logout() { if (!mayLeave()) return; await run(async () => { await api('/admin/logout', { method: 'POST', body: '{}' }); logged.value = false; draft.value = null; selected.value = null; view.value = 'forms'; }); }
function edit(form) { draft.value = clone(form); original.value = JSON.stringify(draft.value); preview.value = false; view.value = 'editor'; error.value = ''; notice.value = ''; }
function create(template = false) { const base = template ? bugTemplate(locale.value) : { title: t('common.untitled'), description: '', thanks: t('common.thanks'), fields: [] }; edit({ ...base, slug: `survey-${crypto.randomUUID().slice(0, 8)}`, state: 'draft' }); original.value = ''; }
function addField(type) { draft.value.fields.push({ id: crypto.randomUUID(), type, label: t('editor.newField', { type: t(fieldTypes[type]) }), description: '', required: false, options: choiceTypes.includes(type) ? [t('editor.optionNumber', { number: 1 }), t('editor.optionNumber', { number: 2 })] : [] }); }
function changeType(field) { if (choiceTypes.includes(field.type) && !field.options.length) field.options = [t('editor.optionNumber', { number: 1 }), t('editor.optionNumber', { number: 2 })]; }
function move(index, delta) { const fields = draft.value.fields; const [f] = fields.splice(index, 1); fields.splice(index + delta, 0, f); }
function remove(index) { if (window.confirm(t('admin.removeConfirm'))) draft.value.fields.splice(index, 1); }
async function save() { await run(async () => { const value = await api(draft.value.id ? `/admin/forms/${draft.value.id}` : '/admin/forms', { method: draft.value.id ? 'PUT' : 'POST', body: JSON.stringify(draft.value) }); draft.value = value; original.value = JSON.stringify(value); await loadForms(); notice.value = value.state === 'published' ? 'admin.savedPublished' : 'admin.saved'; }); }
async function copyLink(slug) { await run(async () => { const link = `${window.location.origin}/f/${slug}`; await navigator.clipboard.writeText(link); notice.value = 'admin.linkCopied'; }); }
async function loadResponses() { const data = await api(`/admin/forms/${responseForm.value.id}/responses?page=${page.value}&status=${encodeURIComponent(filter.value)}`); responses.value = data.items; total.value = data.total; }
async function openResponses(form) { responseForm.value = form; selected.value = null; page.value = 1; filter.value = ''; view.value = 'responses'; await run(loadResponses); }
async function changePage(delta) { page.value += delta; selected.value = null; await run(loadResponses); }
async function saveResponse() { await run(async () => { await api(`/admin/responses/${selected.value.id}`, { method: 'PATCH', body: JSON.stringify({ status: selected.value.status, note: selected.value.note }) }); await loadResponses(); notice.value = 'admin.reviewSaved'; }); }
function formatDate(v) { return new Date(v).toLocaleString(locale.value); }
function summary(item) { return item.snapshot.fields.filter(f => f.type !== 'file').map(f => Array.isArray(item.answers[f.id]) ? item.answers[f.id].join(t('common.listSeparator')) : item.answers[f.id]).filter(Boolean).slice(0, 2).join(' · ') || t('responses.onlyFiles'); }
function answer(item, field) { const value = item.answers[field.id]; return Array.isArray(value) ? value.join(t('common.listSeparator')) || t('responses.unanswered') : value || t('responses.unanswered'); }
</script>
<template>
  <div class="admin-shell">
    <header class="admin-header"><a class="brand" href="/"><span class="brand-mark">{{ t('app.mark') }}</span><span>{{ t('app.brand') }}<span class="brand-divider">/</span><span class="brand-sub">{{ t('admin.subtitle') }}</span></span></a><button v-if="logged" class="text-button" @click="logout" :disabled="busy">{{ t('admin.logout') }}</button><LanguageSwitcher /></header>
    <div v-if="checking" class="state-card">{{ t('common.loading') }}</div>
    <main v-else-if="!logged" class="login-wrap"><form class="login-card" @submit.prevent="login"><div class="eyebrow">{{ t('public.admin') }}</div><h1>{{ t('admin.welcome') }}</h1><p class="muted">{{ t('admin.loginIntro') }}</p><label class="stack-label">{{ t('admin.password') }}<input type="password" v-model="password" autocomplete="current-password" required :placeholder="t('admin.passwordPlaceholder')" /></label><p v-if="error" class="error" role="alert">{{ displayError(error) }}</p><button class="button primary" :disabled="busy">{{ busy ? t('admin.loggingIn') : t('admin.login') }}</button><a href="/" class="muted small">{{ t('admin.fillSurvey') }}</a></form></main>
    <main v-else class="admin-main">
      <div class="notice error" role="alert" v-if="error">{{ displayError(error) }}</div><div class="notice positive" role="status" v-if="notice">{{ t(notice) }}</div>
      <template v-if="view === 'forms'">
        <div class="page-heading"><div><div class="eyebrow">{{ t('admin.eyebrow') }}</div><h1>{{ t('admin.heading') }}</h1><p class="muted">{{ t('admin.intro') }}</p></div><div class="actions"><button class="button" @click="create(true)">{{ t('admin.useTemplate') }}</button><button class="button primary" @click="create()">{{ t('admin.newSurvey') }}</button></div></div>
        <div class="stat-grid"><div class="stat-card"><span>{{ t('admin.allForms') }}</span><strong>{{ forms.length }}</strong></div><div class="stat-card"><span>{{ t('admin.collecting') }}</span><strong>{{ forms.filter(f => f.state === 'published').length }}</strong></div><div class="stat-card"><span>{{ t('admin.received') }}</span><strong>{{ count }}</strong></div></div>
        <div v-if="!forms.length" class="state-card">{{ t('admin.empty') }}</div>
        <div class="form-grid"><article v-for="form in forms" :key="form.id" class="admin-form-card"><div class="card-top"><span class="badge" :class="form.state">{{ t(stateKeys[form.state]) }}</span><span class="muted small">{{ t('common.questions', { count: form.fields.length }) }}</span></div><h2>{{ form.title }}</h2><p class="card-description">{{ form.description || t('admin.noDescription') }}</p><div class="response-count"><strong>{{ form.responseCount }}</strong>{{ t('admin.responsesUnit') }}</div><div class="card-actions"><button @click="edit(form)" class="button">{{ t('admin.edit') }}</button><button @click="openResponses(form)" class="button">{{ t('admin.responses') }}</button><button v-if="form.state === 'published'" @click="copyLink(form.slug)" class="text-button">{{ t('admin.copy') }}</button></div></article></div>
      </template>
      <template v-else-if="view === 'editor'">
        <div class="editor-toolbar"><button class="text-button" @click="back">{{ t('editor.back') }}</button><div class="actions"><span class="muted small">{{ dirty ? t('editor.unsaved') : t('editor.saved') }}</span><button class="button" @click="preview = !preview">{{ preview ? t('editor.continue') : t('editor.preview') }}</button><button class="button primary" :disabled="busy" @click="save">{{ busy ? t('editor.saving') : t('editor.save') }}</button></div></div>
        <div v-if="preview" class="preview-container"><Questionnaire :form="draft" preview /></div>
        <div v-else class="editor-layout">
          <section class="editor-content">
            <div class="panel"><div class="eyebrow">{{ t('editor.info') }}</div><label class="stack-label">{{ t('csv.title') }}<input v-model="draft.title" maxlength="120" /></label><label class="stack-label">{{ t('labels.description') }}<textarea v-model="draft.description" rows="3" maxlength="3000" :placeholder="t('editor.descriptionPlaceholder')"></textarea></label><label class="stack-label">{{ t('labels.thanks') }}<textarea v-model="draft.thanks" rows="2" maxlength="1000"></textarea></label></div>
            <div v-if="!draft.fields.length" class="empty-fields"><span>＋</span><h2>{{ t('editor.firstQuestion') }}</h2><p>{{ t('editor.firstHint') }}</p></div>
            <article v-for="(field, i) in draft.fields" :key="field.id" class="panel field-editor"><div class="field-toolbar"><span class="question-number">{{ String(i + 1).padStart(2, '0') }}</span><select v-model="field.type" @change="changeType(field)" :aria-label="t('editor.type')"><option v-for="(name, type) in fieldTypes" :key="type" :value="type">{{ t(name) }}</option></select><label class="required-toggle"><input type="checkbox" v-model="field.required" />{{ t('common.required') }}</label><div class="actions compact"><button class="icon-button" :disabled="i === 0" @click="move(i, -1)" :aria-label="t('editor.up')">↑</button><button class="icon-button" :disabled="i === draft.fields.length - 1" @click="move(i, 1)" :aria-label="t('editor.down')">↓</button><button class="icon-button danger" @click="remove(i)" :aria-label="t('editor.remove')">×</button></div></div><label class="stack-label">{{ t('labels.question') }}<input v-model="field.label" maxlength="200" /></label><label class="stack-label">{{ t('editor.help') }}<span class="muted">{{ t('common.optional') }}</span><textarea v-model="field.description" rows="2" maxlength="1000" :placeholder="t('editor.helpPlaceholder')"></textarea></label><div v-if="choiceTypes.includes(field.type)" class="option-editor"><label class="stack-label">{{ t('labels.option') }}</label><div v-for="(_, j) in field.options" :key="j" class="option-row"><span class="option-bullet"></span><input v-model="field.options[j]" :aria-label="t('editor.optionNumber', { number: j + 1 })" maxlength="200" /><button class="icon-button" @click="field.options.splice(j, 1)" :disabled="field.options.length <= 2" :aria-label="t('editor.removeOption')">×</button></div><button class="text-button" :disabled="field.options.length >= 30" @click="field.options.push(t('editor.optionNumber', { number: field.options.length + 1 }))">{{ t('editor.addOption') }}</button></div><p v-if="field.type === 'file'" class="hint">{{ t('editor.fileHint') }}</p></article>
          </section>
          <aside class="editor-sidebar"><div class="panel"><h3>{{ t('editor.add') }}</h3><div class="type-grid"><button v-for="(name, type) in fieldTypes" :key="type" class="type-button" :disabled="draft.fields.length >= 30 || (type === 'file' && draft.fields.filter(f => f.type === 'file').length >= 2)" @click="addField(type)"><span>{{ { short: t('editor.textIcon'), long: '☰', single: '◉', multi: '☑', select: '▾', file: '↥' }[type] }}</span>{{ t(name) }}</button></div></div><div class="panel"><h3>{{ t('editor.publish') }}</h3><label class="stack-label">{{ t('editor.state') }}<select v-model="draft.state"><option value="draft">{{ t('editor.draft') }}</option><option value="published">{{ t('editor.published') }}</option><option value="closed">{{ t('editor.closed') }}</option></select></label><label class="stack-label">{{ t('labels.slug') }}<input v-model="draft.slug" maxlength="64" pattern="[a-z0-9-]+" /></label><p class="hint">{{ t('editor.slugHint') }}</p><div class="share-url">{{ formUrl }}</div><button class="button full-width" :disabled="!draft.id || dirty || draft.state !== 'published'" @click="copyLink(draft.slug)">{{ t('editor.copy') }}</button><p class="hint">{{ t('editor.saveHint') }}</p></div></aside>
        </div>
      </template>
      <template v-else-if="view === 'responses'">
        <button class="text-button" @click="back">{{ t('editor.back') }}</button><div class="page-heading"><div><div class="eyebrow">{{ t('responses.eyebrow') }}</div><h1>{{ responseForm.title }}</h1><p class="muted">{{ filter ? t('responses.filtered', { count: total, status: t(statusKeys[filter]) }) : t('responses.total', { count: total }) }}</p></div><div class="actions"><select v-model="filter" :aria-label="t('responses.filter')" @change="page = 1; selected = null; run(loadResponses)"><option value="">{{ t('responses.all') }}</option><option v-for="status in statuses" :key="status" :value="status">{{ t(statusKeys[status]) }}</option></select><a class="button" :href="`/api/admin/forms/${responseForm.id}/export?lang=${locale}`">{{ t('responses.export') }}</a></div></div>
        <div class="responses-layout"><section><div v-if="!responses.length" class="panel muted">{{ busy ? t('common.loading') : t('responses.empty') }}</div><button v-for="item in responses" :key="item.id" class="response-row" :class="{ active: selected?.id === item.id }" @click="selected = clone(item)"><div class="card-top"><span class="badge">{{ t(statusKeys[item.status]) }}</span><span class="small muted">{{ formatDate(item.createdAt) }}</span></div><p>{{ summary(item) }}</p><div class="small muted">#{{ item.id.slice(0, 8).toUpperCase() }} <span v-if="item.attachments.length">{{ t('responses.attachments', { count: item.attachments.length }) }}</span></div></button><div class="pagination"><button class="button" :disabled="page <= 1 || busy" @click="changePage(-1)">{{ t('responses.previous') }}</button><span>{{ page }} / {{ Math.max(1, Math.ceil(total / 30)) }}</span><button class="button" :disabled="page * 30 >= total || busy" @click="changePage(1)">{{ t('responses.next') }}</button></div></section><section class="panel response-detail" v-if="selected"><div class="eyebrow">{{ t('responses.id', { id: selected.id.slice(0, 8).toUpperCase() }) }}</div><h2>{{ selected.snapshot.title }}</h2><p class="small muted">{{ t('responses.version', { date: formatDate(selected.createdAt), version: selected.snapshot.version }) }}</p><dl><template v-for="field in selected.snapshot.fields" :key="field.id"><dt>{{ field.label }}</dt><dd v-if="field.type !== 'file'" class="preserve">{{ answer(selected, field) }}</dd><dd v-else><a v-for="attachment in selected.attachments.filter(a => a.fieldId === field.id)" :key="attachment.id" class="attachment-link" :href="`/api/admin/responses/${selected.id}/files/${attachment.id}`">↓ {{ attachment.name }} <small>{{ t('common.fileSize', { size: (attachment.size / 1024).toFixed(1) }) }}</small></a><span v-if="!selected.attachments.some(a => a.fieldId === field.id)" class="muted">{{ t('responses.notUploaded') }}</span></dd></template></dl><div class="review-controls"><label class="stack-label">{{ t('csv.status') }}<select v-model="selected.status"><option v-for="status in statuses" :key="status" :value="status">{{ t(statusKeys[status]) }}</option></select></label><label class="stack-label">{{ t('csv.note') }}<textarea v-model="selected.note" rows="3" maxlength="10000" :placeholder="t('responses.notePlaceholder')"></textarea></label><button class="button primary" :disabled="busy" @click="saveResponse">{{ t('responses.save') }}</button></div></section><section v-else class="panel detail-placeholder">{{ t('responses.select') }}</section></div>
      </template>
    </main>
  </div>
</template>
